import { defineConfig, devices } from "@playwright/test";

/**
 * Playwright e2e for the Company OS board UI. Loads SSR-generated harness
 * documents (regenerated by `globalSetup` via vitest) in real Chromium at the
 * two key widths, in the host's dark color scheme, and asserts zero console
 * errors + a11y labels while capturing screenshots. No running host required —
 * the board renders entirely from inline styles + a scoped stylesheet.
 */
export default defineConfig({
  testDir: "./tests/ui",
  testMatch: "**/*.e2e.spec.ts",
  globalSetup: "./tests/ui/harness/playwright.globalSetup.ts",
  outputDir: "./tests/ui/.artifacts/test-results",
  reporter: [["list"]],
  use: {
    colorScheme: "dark",
  },
  projects: [
    { name: "desktop", use: { ...devices["Desktop Chrome"], viewport: { width: 1280, height: 900 } } },
    { name: "mobile", use: { ...devices["Pixel 7"] } },
  ],
});
